.

diff --git a/.gitea/workflows/pr-cloudflare-docker-deploy.yml b/.gitea/workflows/pr-cloudflare-docker-deploy.yml
--- a/.gitea/workflows/pr-cloudflare-docker-deploy.yml
+++ b/.gitea/workflows/pr-cloudflare-docker-deploy.yml
@@ -69,6 +69,9 @@ jobs:
         uses: cpanato/vault-installer@main
       - name: Install hvac
         run: pip install hvac
+      - name: Validate Vault Authentication
+        run: |
+          vault status || echo "Vault authentication failed!"
       - name: Ansible Playbook Dry Run
         uses: dawidd6/action-ansible-playbook@v2
         with:
